version: 0.2
phases:
  pre_build:
    commands:
      - ls
      - echo "Creating application version"
      - bucketAndFile=${CODEBUILD_SOURCE_VERSION:13}
      - IFS='/' read -ra S3 <<< "$bucketAndFile"
      - aws elasticbeanstalk create-application-version --application-name sdra --version-label $CODEBUILD_BUILD_NUMBER-$ --source-bundle S3Bucket="${S3[0]}",S3Key="${S3[1]}/${S3[2]}/${S3[3]}"
