version: 0.2
phases:
  install:
    commands:
      - echo "Install"
  build:
    commands:
      - echo "Build started on $(Get-Date)"
      - (Get-ItemProperty "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release
      - nuget restore
      - msbuild
artifacts:
  files:
    - '**/*'
  base-directory: .\AppBundles\Output 
  