version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet publish -c Release
artifacts:
  files:
    - .\bin\Release\netcoreapp3.1\publish\*