version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet publish -c Release -o output
      - ls -lah
      - cat create_creds.sh
      - ./create_creds.sh
artifacts:
  files:
    - '**/*'
  base-directory: ./output
  