version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet publish -c Release -o output
      - echo '{ "Forge": { "clientId": "$FORGE_CLIENT_ID", "clientSecret": "$FORGE_CLIENT_SECRET" } }' > appsettings.Local.json        
artifacts:
  files:
    - '**/*'
  base-directory: ./output
  