version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet publish -c Release -o output
artifacts:
  files:
    - '**/*'
  base-directory: ./output
  