version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - dotnet publish -c Release -o output
      - ./create_creds.sh > output/appsettings.Local.json
artifacts:
  files:
    - '**/*'
  base-directory: ./output
  