FROM mcr.microsoft.com/dotnet/sdk:6.0
COPY app/ app/
COPY amazon-cloudwatch-agent.deb /app
WORKDIR /app

RUN dpkg -i -E ./amazon-cloudwatch-agent.deb
COPY /AWS-CICD/amazon-cloudwatch-agent.json /opt/aws/amazon-cloudwatch-agent/etc/
COPY /AWS-CICD/commands.sh .
RUN chmod +x commands.sh

ENTRYPOINT ["./commands.sh"]
#ENTRYPOINT ["/bin/bash"]