/* eslint-disable no-undef */

module.exports = {
     xpButtonReset : '//div[3]/button[1]',
     xpButtonUpdate : '//div[3]/button[2]',
     xpDivForgeViewer : '//*[@id="ForgeViewer"]',
     xpLinkAdskForge : '//div[1]/div[1]/a',
     xpComboProjects : '//p',
     xpProjectConveyor : '//ul/li[1]/span[2]',
     xpProjectWrench : '//ul/li[2]/span[2]',
     xpProjectList : '//div/div[2]',
     xpButtonLog : '//div/div[1]/button',
     xpStripeElement : '//*[@id="model"]/div/div[2]/div[1]',
     xpDivParameterList : '//*[@id="model"]/div/div[1]/div[1]',
     xpDivParameterContainer : '//*[@id="model"]/div/div[1]',
     xpDivProjectsButton : '//div[3]/div/div[1]/div',
     xpPopUpLog : '//div/div[2]',
     xpMenuProjectsName : '//ul/span',
     xpViewerCanvas : '//*[@id="ForgeViewer"]/div/div/div[1]/canvas',
     projectsTab : locate('li').find('p').withText('Projects'),
     modelTab : locate('li').find('p').withText('Model'),
     bomTab : locate('li').find('p').withText('BOM'),
     drawingTab : locate('li').find('p').withText('Drawing'),
     downloadsTab : locate('li').find('p').withText('Downloads'),
};