version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
  build:
    commands:
      - echo Tests started on `date`
      - echo Building Docker test image...
      - docker build --build-arg FORGE_CLIENT_ID=${FORGE_CLIENT_ID} --build-arg FORGE_CLIENT_SECRET=${FORGE_CLIENT_SECRET} --tag test-runner -f ./AWS-CICD/Dockerfile.test .
      - echo Running container that executes the tests...
      - docker container run --ipc=host --security-opt seccomp=AWS-CICD/chrome.json test-runner
  post_build:
    commands:
      - echo Tests completed on `date`
artifacts:
  files:
