version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "Buildspec-mig-image initialize"
      - echo Build started on `date`
      - IMAGE_TAG=${CommitId:0:7}
      - wget https://s3.us-west-2.amazonaws.com/amazoncloudwatch-agent-us-west-2/debian/amd64/latest/amazon-cloudwatch-agent.deb
      - echo Building Docker production image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f ./AWS-CICD/Dockerfile-mig.image .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - sed -i 's/sdra:latest/'$IMAGE_REPO_NAME:$IMAGE_TAG'/g' ./AWS-CICD/Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
    - '.ebextensions/**/*'
  base-directory: AWS-CICD