version: 0.2
phases:
  build:
    commands:
      - echo "Buildspec-deploy initialize"
      - cd AWS-CICD/Deploy
      - npm install
      - node deploy-version.js $pipelineName $PipelineExecutionId $CommitId "SDRA" $environmentName