version: 0.2
phases:
  build:
    commands:
      - cd AWS-CICD/Deploy
      - npm install
      - node deploy-version.js $pipelineName $PipelineExecutionId $CODEBUILD_BUILD_NUMBER "$appName" $environmentName