$userIndex=$Env:CODEBUILD_BUILD_NUMBER % $Env:UserCount
echo $userIndex
$FORGE_CLIENT_ID=(Get-ChildItem -Path Env:\FORGE_CLIENT_ID$userIndex).Value
echo $FORGE_CLIENT_ID
$Env:FORGE_CLIENT_ID=$FORGE_CLIENT_ID
echo $Env:FORGE_CLIENT_ID
$FORGE_CLIENT_SECRET=(Get-ChildItem -Path Env:\FORGE_CLIENT_SECRET$userIndex).Value
echo $FORGE_CLIENT_SECRET
$Env:FORGE_CLIENT_SECRET=$FORGE_CLIENT_SECRET
echo $Env:FORGE_CLIENT_SECRET
